### ISSUE TITLE
Cannot run dev

### ISSUE THREAD

**Issue by priambudiLB** [Lzadhito/pokemonnya-dito#3]
React Apollo Error: Invariant Violation: Could not find “client” in the context or passed in as an option

Steps to reproduce
- clone repo
- cd pokemonnya-dito
- npm install
- npm run dev

Apparently [someone](https://stackoverflow.com/a/58476065) has solved this issue.

**Comment by Lzadhito** [comment]
Hello @priambudiLB , thank you for trying this repo. I seldom use npm in this project while I use yarn daily, it might be some mixed package between the two. Please try using yarn and notice me if there is another error. Thank you!
